import { Customer } from "../../models/customer.js";
import { ProductCategory } from "../../models/productCategory.js";

const customers = [
  {
    _id: "6499c065722353f7b1585065",
    companyName: "NovaraTech",
    country: "France",
    region: "Normandy",
    city: "Rouen",
    zipcode: 76000,
    adress: "Rue de Rouen",
    contactPersonName: "Leon",
    contactPersonEmail: "leon@novaratech.com",
    accountType: "CEO",
    numberOfEmployees: 400,
    revenue: 40_000_000,
    showOnMarketplace: true,
    image: "/logos/logo1.jpg",
    description: "NovaraTech, hailing from the historic city of Rouen in France, stands at the forefront of technological innovation and supply. We specialize in providing advanced, reliable, and customized tech solutions that cater to the ever-evolving needs of the digital world. With a dedicated team of experts and professionals, we strive to be trailblazers in various technology domains, including IoT, AI, and cloud computing.",
    productCategories: {},
    score: 7.3,
  },
  {
    _id: "6499c401722353f7b1585066",
    companyName: "Vortexa",
    country: "Germany",
    region: "NRW",
    city: "Essen",
    zipcode: 45136,
    adress: "Ruhrallee 12",
    contactPersonName: "Markus",
    contactPersonEmail: "markus@vortexa.com",
    accountType: "CEO",
    numberOfEmployees: 100,
    revenue: 10_000_000,
    showOnMarketplace: true,
    image: "/logos/logo2.jpg",
    description: "Based in the bustling city of Essen, Germany, Vortexa is a dynamic player in the world of digital innovation. We are committed to creating transformative technological solutions that streamline operations and enhance productivity. Vortexa's expertise spans across various sectors, including AI, robotics, and software development, offering a diverse array of products and services designed with our clients' needs in mind.",
    productCategories: {},
    score: 7.8,
  },
  {
    _id: "6499c51b722353f7b1585067",
    companyName: "Munich Coffee",
    country: "Germany",
    region: "Bavaria",
    city: "Munich",
    zipcode: 80801,
    adress: "Leopoldstraße 12",
    contactPersonName: "Alex",
    contactPersonEmail: "Alex@munichcoffee.com",
    accountType: "CEO",
    numberOfEmployees: 50,
    revenue: 5_000_000,
    showOnMarketplace: true,
    image: "/logos/logo3.jpg",
    description: "Located in the bustling city of Munich, Germany, Munich Coffee is your go-to destination for premium coffee experiences. Nestled in the heart of Bavaria, our coffee shop is a testament to quality, tradition, and the art of coffee making. Our dedicated team is passionate about delivering outstanding service and quality coffee, a dedication that reflects in our 4.5-star rating. Visit us at our Leopoldstraße 12 location to experience the richness of flavors we offer and the warm, welcoming ambiance we pride ourselves on. At Munich Coffee, every cup tells a story, come create yours with us.",
    productCategories: {},
    score: 8.9,
  },
  {
    _id: "7439c51b722353f7b1507067",
    companyName: "SteelWorks",
    country: "China",
    region: "Guangdong",
    city: "Guangzhou",
    zipcode: 510000,
    address: "123 Iron Foundry Rd",
    contactPersonName: "Li Wei",
    contactPersonEmail: "li.wei@steelworks.com",
    accountType: "CEO",
    numberOfEmployees: 300,
    revenue: 20000000,
    showOnMarketplace: true,
    image: "/logos/SteelWorks.png",
    description: "SteelWorks, based in Guangzhou, China, is a premier manufacturer of high-quality iron products. With a dedicated workforce of 300, we pride ourselves in our commitment to quality and innovation. Our products are utilized in a variety of industries across the globe, underscoring our reputation as a trusted supplier in the iron manufacturing sector.",
    productCategories: {},
    score: 4.3
  },
  {
    _id: "8752c63b726758f8b1398058",
    companyName: "The Iron Company",
    country: "Russia",
    region: "Sverdlovsk Oblast",
    city: "Yekaterinburg",
    zipcode: 620014,
    address: "35 Metallurgov Street",
    contactPersonName: "Anatoly Ivanov",
    contactPersonEmail: "ivanov@theironcompany.com",
    accountType: "CEO",
    numberOfEmployees: 400,
    revenue: 30000000,
    showOnMarketplace: true,
    image: "/logos/the_iron_company.png",
    description: "The Iron Company is a key player in the global iron industry, located in the heart of Russia, Yekaterinburg. Committed to the highest standards of quality, we have over 400 experienced employees producing iron that meets the demands of our international clientele. Our products have become synonymous with durability and precision, making us a trusted choice for iron supplies.",
    productCategories: {},
    score: 4.7
  },
  {
    _id: "8853d75a927858f9c3409059",
    companyName: "Shirts of Tomorrow",
    country: "Bangladesh",
    region: "Dhaka Division",
    city: "Dhaka",
    zipcode: 1212,
    address: "88 Fabric Avenue",
    contactPersonName: "Rahim Uddin",
    contactPersonEmail: "uddin@shirtsoftomorrow.com",
    accountType: "CEO",
    numberOfEmployees: 200,
    revenue: 15000000,
    showOnMarketplace: true,
    image: "/logos/shirts_of_tomorrow.png",
    description: "Shirts of Tomorrow, stationed in the vibrant city of Dhaka, Bangladesh, is a pioneering manufacturer of contemporary and innovative shirts. Our team of 200 dedicated professionals works relentlessly to bring to life the latest trends in the fashion world. We are passionate about providing superior quality shirts that resonate with the dynamic style of tomorrow.",
    productCategories: {},
    score: 3.0
  },
  {
    _id: "9f85d32a129040f9b2509798",
    companyName: "Twists and Ties",
    country: "United Kingdom",
    region: "England",
    city: "London",
    zipcode: 12345,
    address: "1 Fashion Street",
    contactPersonName: "Arthur Twist",
    contactPersonEmail: "arthur.twist@twistsandties.com",
    accountType: "CEO",
    numberOfEmployees: 150,
    revenue: 9000000,
    showOnMarketplace: true,
    image: "/logos/twists_and_ties.png",
    description: "Twists and Ties, positioned in the heart of fashionable London, weaves together tradition and innovation to craft exquisite neckwear. Our talented artisans marry timeless techniques with modern design to create ties that not only complement an outfit, but become the cornerstone of it. Experience a world where elegance twirls with contemporary style, and superior craftsmanship ties it all together.",
    productCategories: {},
    score: 8.2
  },
  {
    _id: "7a26d68b1230b1e9b6543210",
    companyName: "Best Shirts India",
    country: "India",
    region: "Maharashtra",
    city: "Mumbai",
    zipcode: 400001,
    address: "123 Fashion Boulevard",
    contactPersonName: "Ravi Sharma",
    contactPersonEmail: "ravi.sharma@bestshirtsindia.com",
    accountType: "CEO",
    numberOfEmployees: 500,
    revenue: 15000000,
    showOnMarketplace: true,
    image: "/logos/best_shirts_india.png",
    description: "Nestled in the vibrant city of Mumbai, Best Shirts India captures the essence of India's rich textile history while embracing the dynamism of modern design. We breathe life into fabrics, crafting shirts that echo the pulse of fashion-forward India. Our skilled artisans harmonize traditional techniques with innovative patterns, crafting shirts that serve not just as a piece of clothing but a canvas of artistry. Walk into a world where tradition meets trend, only at Best Shirts India.",
    productCategories: {},
    score: 5.5
  },
  {
    _id: "8b25c68b1230b1e9b6965321",
    companyName: "Fresh Alp Milk",
    country: "Austria",
    region: "Alps",
    city: "Innsbruck",
    zipcode: 6020,
    address: "Alpine Meadows 1,2,3",
    contactPersonName: "Hans Müller",
    contactPersonEmail: "hans.muller@freshalpmilk.com",
    accountType: "CEO",
    numberOfEmployees: 200,
    revenue: 12000000,
    showOnMarketplace: true,
    image: "/logos/fresh_alp_milk.png",
    description: "Fresh Alp Milk is not just a brand, it's a tribute to the rich, unspoiled landscapes of the Alps where our journey began. With farms in Austria, Switzerland, and Germany, our milk is a harmonious blend of pristine Alpine traditions and modern dairy practices. The milk is harvested from cows that graze freely on Alpine pastures, lending it a unique, creamy flavor that is rich in nutrients. Every drop of Fresh Alp Milk embodies the pure essence of the Alps, bringing you closer to nature's bounty.",
    productCategories: {},
    score: 9.3
  },
  {
    _id: "9c35d78e1341c2f0b7976422",
    companyName: "Premium Shirts Turkey",
    country: "Turkey",
    region: "Marmara",
    city: "Istanbul",
    zipcode: 34116,
    address: "Eminönü Pier No.5,6,7",
    contactPersonName: "Ahmet Yılmaz",
    contactPersonEmail: "ahmet.yilmaz@premiumshirtsturkey.com",
    accountType: "CEO",
    numberOfEmployees: 350,
    revenue: 25000000,
    showOnMarketplace: true,
    image: "/logos/premium_shirts_turkey.png",
    description: "Premium Shirts Turkey is a renowned textile brand with deep roots in Turkey's rich history of textile manufacturing. Located in the bustling city of Istanbul, we craft premium quality shirts that blend traditional artistry with contemporary design. Our shirts are loved by customers around the globe for their exceptional quality, comfort, and style. With sustainable practices at our core, every shirt we make is a testament to our commitment to responsible manufacturing. Premium Shirts Turkey - where tradition meets trend.",
    productCategories: {},
    score: 8.0
  },
  {
    _id: "6499c51b722353f7b1585069",
    __v: 27,
    productCategories: [],
    companyName: "Fashion Oasis",
  },
];

export const seedCustomers = async () => {
    console.log("seeding Customers...");
    const productCategories = await ProductCategory.find({});
    return await Promise.all(customers.map(async (customer: any, index) => {
      try {
        customer.productCategories = productCategories;
        await Customer.create(customer);
        return customer;
      } catch (error) {
        console.error(error);
      }
      return false;
    }));
  };
  
